templates/base.html
=> Corrected typo, removed '6' from title

apps/publisher/views.py
Fixes #68 
Make the publication count show the number of publications of the selected project.
=> Fix publication count

apps/publisher/forms.py, requirements.txt
=> Update Django and replace reCAPTCHA v1 with v2

templates/site/nav.html
=> Add 'all' option for view menu

templates/snippets/load_publications.html
=> Add BibTex links for publications that load after scrolling down the page.

pubhub-static/css/new_publication.css, templates/site/edit.html, templates/site/publication_details.html, templates/snippets/authorForm.html, templates/snippets/publicationForm.html
@taylor13
Resolves #108 
Resolves #109 
Here is the submission page with the changes suggested in the above issues.  These changes can be seen on our development server.
=> Updates to publication submission page

scripts/journals.py
=> Add journal 'ICES Journal of Marine Science'

scripts/journals.py
=> Add journal 'Geoscience Data Journal'

scripts/journals.py
=> Add journal 'Scientific Reports'

apps/publisher/views.py
Fixes #138  
The issue was caused by the DOI not being resubmitted with the rest of the publication info when the form is deemed invalid.
=> Fix issue where pending DOI is not removed from the list if submitted after correcting an invalid form

scripts/journals.py
=> Add journal 'Progress in Earth and Planetary Science'

scripts/journals.py
=> Add journal 'Nature Communications'

scripts/journals.py
=> Add journal 'Journal of Geophysical Research: Oceans'

scripts/journals.py
=> Add journal 'Earth's Future'

scripts/journals.py
=> Add journal Global and Planetary Change

scripts/journals.py
=> Add journal 'Data in Brief'

scripts/journals.py
=> Add journal 'Water'

scripts/journals.py
=> Add journal "AGU Advances"

scripts/journals.py
Resolves #168 
Adds the journal "Sustainability". https://www.mdpi.com/journal/sustainability
@durack1 @taylor13  Please review
=> Add journal "Sustainability"

pubhub-static/js/google_analytics_pcmdi.js, templates/base.html
=> Add PCMDI Google Analytics script to site

scripts/journals.py
=> Add journal "npj Climate and Atmospheric Science"

scripts/journals.py
=> Add journal 'Frontiers in Earth Science'

scripts/journals.py
=> Add journal 'Conservation Science and Practice'

scripts/journals.py
=> Add journal "Biological Conservation"

scripts/journals.py
=> Add journal "Forensic Science International: Reports"

scripts/journals.py
=> Add journals 

scripts/journals.py
=> Add journal 'Earth and Space Science'

scripts/journals.py
Resolves #207 #200 
Adds the following journals:
* [Past Global Changes Magazine](https://www.pastglobalchanges.org/publications/pages-magazines/pages-magazine)
* [Scientific Data](https://www.nature.com/sdata/)
=> Add journals

pubhub/templates/site/footer.html
=> Update Docker branch
